language: python

matrix:
  include:
    - python: 2.7
      os: linux
      env: _REZ_SHELL=bash

install:
  - 'if [ "$_REZ_SHELL" == "tcsh" ]; then sudo apt-get install tcsh; fi'
  - 'python ./install.py ../rez_install'
  # Test with rez installed as "rez_install" and "rez" packages
  - 'python ./install.py -p rez_install ../packages'
  - 'python ./install.py -P ../packages'

script:
  - 'find ../rez_install/ ../packages/ -name rez-selftest -exec {} -s $_REZ_SHELL \;'
