# JUST AN EXPERIMENT - delete/replace as necessary before merge
name: Experimenting with actions - PR 579
on: [push]

jobs:
  linux:
    name: Ubuntu - install prod. venv
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['2.7', '3.7']
        package-name: ['rez', 'foo']
        rez-shell: ['bash', 'tcsh']

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64

    - name: Check install.py help
      run: |
        python install.py --help

    - name: Install as rez package into HOME/packages
      run: |
        INSTALL_LOG=$(mktemp)
        if [ "${{ matrix.package-name }}" == "rez" ]
        then
          INSTALL_FLAGS="-p"
        else
          INSTALL_FLAGS="-P ${{ matrix.package-name }}"
        fi
        python install.py ${INSTALL_FLAGS} ${HOME}/packages |& tee ${INSTALL_LOG}
        # Setup rez activation scripts
        echo "export PATH=${PATH}:$(sed -n '/to .PATH:/ {n;p;q}' ${INSTALL_LOG})" > setup-rez.sh

    - name: View rez rez package
      run: |
        source setup-rez.sh
        find ${HOME}/packages -maxdepth 5
        rez view ${{ matrix.package-name }}

    - name: Bind Python and check rez env
      run: |
        source setup-rez.sh
        rez bind python
        rez env ${{ matrix.package-name }} -- rez context

    - name: rez-selftest
      env:
        _REZ_SHELL: ${{ matrix.rez-shell }}
      run: |
        source setup-rez.sh
        if [ "$_REZ_SHELL" == "tcsh" ]; then sudo apt-get install tcsh; fi
        $(rez env ${{ matrix.package-name }} -- which rez-selftest) -s ${_REZ_SHELL}

    # - name: Install in Python Docker Image
