name: Sphinx
on:
  push:
    branches:
      - master
    paths:
      - 'docs/**'
      - 'src/**'
  pull_request:
    paths:
      - 'docs/**'
      - 'src/**'


jobs:
  build:
    name: Sphinx HTML Artifact
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Sphinx Build (no Docker container)
        run: HOSTNAME="rez-sphinx-build" bash docs/entrypoint.sh

      - uses: actions/upload-artifact@master
        with:
          name: html-docs
          path: docs/_build

  publish:
    name: Publish to GitHub pages
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    needs: build

    steps:
      - uses: actions/download-artifact@master
        with:
          name: html-docs
          path: .

      - name: Setup git repository
        run: |
          git config --global color.ui always
          git init .
          git config --global user.name "github.com/${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@${{ github.sha }}"
          git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git"
          git checkout -B gh-pages

      - name: Git add and commit
        run: |
          git add .
          git commit \
              -m "Generated from GitHub "${{ github.workflow }}" Workflow" \
              -m "See https://github.com/${{ github.repository }}/runs/${GITHUB_ACTION}"

      - name: Git force push gh-pages
        run: git push --force origin gh-pages