name: WWFX
on: 
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '* * * * 0'

jobs:
  auto-update:
    name: Auto Update
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Git remotes
      run: |
        git config --global color.ui always
        git remote rename origin wwfxuk
        git remote add j0yu https://github.com/j0yu/bleeding-rez.git
        git remote add origin https://github.com/nerdvegas/rez.git
        git remote update

    - name: Auto Update All
      shell: bash
      run: exec src/support/wwfx/auto-update.sh

    - run: git show
    - run: git log --graph --oneline --decorate -100 --all
